library(shiny)
library(descriptr)
library(dplyr)

shinyServer(function(input, output, session) {

    source('logic/logic_link.R', local = T)
    source('logic/logic_upload.R', local = T)
    source('logic/logic_transform.R', local = T)
    source('logic/logic_view.R', local = T)
    source('logic/logic_screen.R', local = T)
    source('logic/logic_summary.R', local = T)
    source('logic/logic_freq_qual.R', local = T)
    source('logic/logic_cross.R', local = T)
    source('logic/logic_freq_quant.R', local = T)
    source('logic/logic_group_summary.R', local = T)
    source('logic/logic_mult1.R', local = T)
    source('logic/logic_mult2.R', local = T)
    source('logic/logic_binom.R', local = T)
    source('logic/logic_chisq.R', local = T)
    source('logic/logic_f.R', local = T)
    source('logic/logic_t.R', local = T)
    source('logic/logic_norm.R', local = T)
    source('logic/logic_bar.R', local = T)
    source('logic/logic_bar2.R', local = T)
    source('logic/logic_box.R', local = T)
    source('logic/logic_box2.R', local = T)
    source('logic/logic_hist.R', local = T)
    source('logic/logic_pie.R', local = T)
    source('logic/logic_pie3d.R', local = T)
    source('logic/logic_scatter.R', local = T)
    source('logic/logic_line.R', local = T)
})
